@startuml
'https://plantuml.com/use-case-diagram
header Mancala Use Case Diagram

:Admin/Computer: as Admin
(Select a cup) as (P1_Select)
(Select a cup) as (P2_Select)
(Marbles moved) as (P1_Move)
(Marbles moved) as (P2_Move)

'Use Case 1 - Player 1 selects a cup that has marbles
Player1 -right-> (P1_Select)
'Use Case 2 - Admin moves the marbles
(P1_Select) --> (P1_Move)
'Use Case 3 - Player gets another chance
(P1_Select) <|-- (Select again)
'Use Case 2 repeated
Admin --> (P1_Move)
'Use Case 4 - Switch Player
(P1_Move) --> Player2

'Use Case 5 - Player 2 selects a cup that has marbles
Player2 --> (P2_Select)
'Use Case 2 repeated
(P2_Select) --> (P2_Move)
'Use Case 3 repeated
(P2_Select) <|-- (Select again )
'Use Case 2 repeated
Admin -up-> (P2_Move)
'Use Case 4 repeated
(P2_Move) --> Player1

note right of Admin
After moving the marbles
if all the cups of any player
become empty then the game ends.
Marbles are counted in each
player's Mancala and the player
with max marbles wins.
Equal no. of marbles in each
player's Mancala means a tie.
end note

note "If last marble drop is in the player's Mancala" as N1
(Select again) .. N1
N1 .. (Select again )

note "Marbles from the selected cup are\npicked and dropped in consecutive cups\n(including the player's Mancala)\nin counter-clockwise direction" as N2
(P1_Move) .. N2
N2 .. (P2_Move)
@enduml