@startuml
'https://plantuml.com/activity-diagram-beta
header Mancala Activity Diagram
start
:Player 1 Turn;
while (Moves available?) is (Yes)
    while (continue playing) is (Yes)
        'Use Case 1 and 5 - Player 1/2 selects a cup that has marbles
        :Choose a cup that has marbles;
        'Use Case 2 - Admin moves the marbles
        :Place marbles in cups in counter-clockwise direction;
        if (Is last marble drop in your empty cup?) then (Yes)
            :Opponent's marbles are taken (if any);
            break;
        else (No)
            if (Is last marble drop in your Mancala?) then (No)
                break;
            else (Yes)
                'Use Case 3 - Player gets another chance
                :Player gets another chance;
            endif
        endif
    endwhile (No)
    'Use Case 4 - Switch Player
    :Switch player;
endwhile (No)
if (Both the players have equal marbles in their Mancala?) is (Yes) then
  :It's a tie;
else (No)
  :Player with max marbles in their Mancala wins;
endif
stop
@enduml
